name: BigQuery Technical Guide
subtitle: A practical guide for making decisions about your BigQuery deployment
category-list: [(0) Introduction, (1) Resource Concepts, (2) BigQuery Internals, (3) Working with BigQuery, (4) Data Governance, (5) Monitoring & Optimizing]


